### ISSUE TITLE
I want to know how to use message

### ISSUE THREAD

**Issue by huccct** [vangleer/vangle#1]

**Comment by vangleer** [comment]
http://vangleer.gitee.io/vangle/zh/component/message.html

**Comment by huccct** [comment]
this use method is wrong

**Comment by huccct** [comment]
this is only in the monorepo use.

**Comment by vangleer** [comment]
Oh, I didn't notice that, you can import it like this  `import { VanMessage } from 'vangle'`

**Comment by huccct** [comment]
please add a WeChat, cuz I have some packaging problems.

**Comment by vangleer** [comment]
my wechat `hwt965002107`

**Comment by huccct** [comment]
all right
